config/routes.rb
Depot::Application.routes.draw do
  get "admin" => 'admin#index'
  
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get "store/index"

  resources :products do
    get :who_bought, :on => :member
  end

  root to: 'store#index', as: 'store'

end

app/views/layouts/application.html.erb
<!-- START:head -->
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<!-- END:head -->
<body class="<%= controller.controller_name %>">
  <div id="banner">
    <%= image_tag("logo.png") %>
    <%= @page_title || "Pragmatic Bookshelf" %>
  </div>
  <div id="columns">
    <div id="side">
    <!-- START_HIGHLIGHT -->
    <% if @cart %>
      <!-- START:hidden_div -->
      <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
        <%= render @cart %>
      <% end %>
    <!-- END:hidden_div -->
    <% end %>
<!-- END_HIGHLIGHT -->
    <%= link_to 'Home', store_path %><br/>
    <a href="http://www..../faq">Questions</a><br/>
    <a href="http://www..../news">News</a><br/>
    <a href="http://www..../contact">Contact</a><br/>
    <br/>
    <% if session[:user_id] %>
      <%= link_to 'Orders',   orders_path   %><br/>
      <%= link_to 'Products', products_path %><br/>
      <%= link_to 'Users',    users_path     %><br/>
      <br/>
      <%= link_to button_to 'Logout', logout_path, :method => :delete %>
    <% else %>
      <%= link_to 'Login', login_path  %>
    <% end %>
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>
</body>
</html>